// ══════════════════════════════════════════════════════════════
//  Root barrel — 所有类型统一入口
//  用法:
//    import { zEmployeeCreate, type EmployeeCreate } from '@/types'
//    import { zApiResponse, zPaginatedData } from '@/types'
// ══════════════════════════════════════════════════════════════

// Common
export {
  zApiResponse,
  zApiResponseEmpty,
  zPaginationParams,
  zPaginatedData,
  auditMixin,
  softDeleteMixin,
  zDateString,
  zTimeString,
  zHexColor,
  zPhone,
  zIdCard,
  zNonNegativeNumber,
  zMasked,
  zStatusCode,
  type PaginationParams,
} from "./common.js";

// Auth
export {
  zLoginInput,
  zLoginOutput,
  zUserCreate,
  zUser,
  type LoginInput,
  type LoginOutput,
  type UserCreate,
  type User,
} from "./auth.js";

// Org
export {
  zDepartmentCreate,
  zDepartmentUpdate,
  zDepartment,
  zDepartmentQuery,
  zDepartmentTreeNode,
  zDepartmentTree,
  zPositionCreate,
  zPositionUpdate,
  zPosition,
  zRankCreate,
  zRankUpdate,
  zRank,
  type DepartmentCreate,
  type DepartmentUpdate,
  type Department,
  type DepartmentQuery,
  type DepartmentTreeNode,
  type DepartmentTree,
  type PositionCreate,
  type PositionUpdate,
  type Position,
  type RankCreate,
  type RankUpdate,
  type Rank,
} from "./org.js";

// Employee
export {
  EmployeeStatusEnum,
  zEmployeeCreate,
  zEmployeeUpdate,
  zEmployeeBase,
  zEmployeeListItem,
  zEmployeeFullDetail,
  zEmployeeQuery,
  zRegularizeInput,
  zResignInput,
  zBatchImportResult,
  type EmployeeStatus,
  type EmployeeCreate,
  type EmployeeUpdate,
  type EmployeeBase,
  type EmployeeListItem,
  type EmployeeFullDetail,
  type EmployeeQuery,
  type RegularizeInput,
  type ResignInput,
  type BatchImportResult,
} from "./employee.js";

// Permissions
export {
  zRoleCreate,
  zRoleUpdate,
  zRole,
  zRolePermissionAssign,
  zPermission,
  zUserRoleAssign,
  type RoleCreate,
  type RoleUpdate,
  type Role,
  type RolePermissionAssign,
  type Permission,
  type UserRoleAssign,
} from "./permissions.js";

// Schedules
export {
  zShiftTemplateCreate,
  zShiftTemplateUpdate,
  zShiftTemplate,
  zRotationPattern,
  zRotationRuleCreate,
  zRotationRule,
  zScheduleCreate,
  zScheduleUpdate,
  zSchedule,
  zScheduleGenerateInput,
  zScheduleGenerateResult,
  zScheduleClearRange,
  zScheduleQuery,
  zScheduleConflict,
  type ShiftTemplateCreate,
  type ShiftTemplateUpdate,
  type ShiftTemplate,
  type RotationPattern,
  type RotationRuleCreate,
  type RotationRule,
  type ScheduleCreate,
  type ScheduleUpdate,
  type Schedule,
  type ScheduleGenerateInput,
  type ScheduleGenerateResult,
  type ScheduleClearRange,
  type ScheduleQuery,
  type ScheduleConflict,
} from "./schedules.js";

// Attendance
export {
  zClockType,
  zAttendanceRecordCreate,
  zAttendanceRecord,
  zAttendanceRecordQuery,
  zAttendanceSummaryGenerate,
  zAttendanceSummary,
  zAttendanceSummaryQuery,
  type ClockType,
  type AttendanceRecordCreate,
  type AttendanceRecord,
  type AttendanceRecordQuery,
  type AttendanceSummaryGenerate,
  type AttendanceSummary,
  type AttendanceSummaryQuery,
} from "./attendance.js";

// Leave
export {
  zLeaveType,
  zLeaveTimeHalf,
  zLeaveQuotaInit,
  zLeaveQuota,
  zLeaveQuotaQuery,
  zLeaveRequestCreate,
  zLeaveRequestUpdate,
  zLeaveRequestStatus,
  zLeaveRequestBase,
  zLeaveRequestListItem,
  zLeaveRequestQuery,
  zLeaveApproval,
  zLeaveRejection,
  zApprovalChainNode,
  zApprovalChain,
  type LeaveType,
  type LeaveTimeHalf,
  type LeaveQuotaInit,
  type LeaveQuota,
  type LeaveQuotaQuery,
  type LeaveRequestCreate,
  type LeaveRequestUpdate,
  type LeaveRequestStatus,
  type LeaveRequestBase,
  type LeaveRequestListItem,
  type LeaveRequestQuery,
  type LeaveApproval,
  type LeaveRejection,
  type ApprovalNodeStatus,
  type ApprovalChainNode,
  type ApprovalChain,
} from "./leave.js";

// Salary
export {
  zSalaryPasswordVerify,
  zSalaryPasswordVerifyResult,
  zSalaryPasswordSet,
  zSalaryItemType,
  zSalaryItemCreate,
  zSalaryStructureCreate,
  zSalaryStructureUpdate,
  zSalaryStructure,
  zSalaryStructureAssign,
  zPayslipItem,
  zPayslipListItem,
  zPayslipFullDetail,
  zPayslipGenerate,
  zPayslipQuery,
  zSalaryAuditAction,
  zSalaryAuditLog,
  zSalaryAuditLogQuery,
  type SalaryPasswordVerify,
  type SalaryPasswordVerifyResult,
  type SalaryPasswordSet,
  type SalaryItemType,
  type SalaryItemCreate,
  type SalaryStructureCreate,
  type SalaryStructureUpdate,
  type SalaryStructure,
  type SalaryStructureAssign,
  type PayslipItem,
  type PayslipListItem,
  type PayslipFullDetail,
  type PayslipGenerate,
  type PayslipQuery,
  type SalaryAuditAction,
  type SalaryAuditLog,
  type SalaryAuditLogQuery,
} from "./salary.js";

// Expense
export {
  zExpenseType,
  zExpenseClaimStatus,
  zExpenseClaimCreate,
  zExpenseClaimUpdate,
  zExpenseClaim,
  zExpenseClaimQuery,
  type ExpenseType,
  type ExpenseClaimStatus,
  type ExpenseClaimCreate,
  type ExpenseClaimUpdate,
  type ExpenseClaim,
  type ExpenseClaimQuery,
} from "./expense.js";

// Training
export {
  zTrainingType,
  zTrainingCourseStatus,
  zTrainingCourseCreate,
  zTrainingCourseUpdate,
  zTrainingCourse,
  zTrainingCourseQuery,
  zTrainingEnrollment,
  zTrainingCompletion,
  zTrainingRecord,
  type TrainingType,
  type TrainingCourseStatus,
  type TrainingCourseCreate,
  type TrainingCourseUpdate,
  type TrainingCourse,
  type TrainingCourseQuery,
  type TrainingEnrollment,
  type TrainingCompletion,
  type TrainingRecord,
} from "./training.js";

// KB
export {
  zKbCategory,
  zKbDocumentCreate,
  zKbDocument,
  zKbDocumentQuery,
  zKbPreviewUrl,
  type KbCategory,
  type KbDocumentCreate,
  type KbDocument,
  type KbDocumentQuery,
  type KbPreviewUrl,
} from "./kb.js";

// Workflow
export {
  zNodeType,
  zAssigneeType,
  zSignType,
  zTimeoutAction,
  zOperator,
  zPosition,
  zCondition,
  zTemplateNode,
  zEdge,
  zWorkflowTemplateCreate,
  zWorkflowTemplate,
  zWorkflowInstanceStatus,
  zWorkflowInstanceCreate,
  zWorkflowInstanceNode,
  zWorkflowInstance,
  zWorkflowInstanceQuery,
  zWorkflowApprove,
  zWorkflowReject,
  zWorkflowDelegate,
  zWorkflowAddSigner,
  type NodeType,
  type AssigneeType,
  type SignType,
  type TimeoutAction,
  type Operator,
  type Position,
  type Condition,
  type TemplateNode,
  type Edge,
  type WorkflowTemplateCreate,
  type WorkflowTemplate,
  type WorkflowInstanceStatus,
  type WorkflowInstanceCreate,
  type WorkflowInstanceNode,
  type WorkflowInstance,
  type WorkflowInstanceQuery,
  type WorkflowApprove,
  type WorkflowReject,
  type WorkflowDelegate,
  type WorkflowAddSigner,
} from "./workflow.js";

// Messages
export {
  zMessageType,
  zMessage,
  zMessageQuery,
  zAnnouncementTargetType,
  zAnnouncementStatus,
  zAnnouncementCreate,
  zAnnouncementUpdate,
  zAnnouncement,
  zAnnouncementQuery,
  type MessageType,
  type Message,
  type MessageQuery,
  type AnnouncementTargetType,
  type AnnouncementStatus,
  type AnnouncementCreate,
  type AnnouncementUpdate,
  type Announcement,
  type AnnouncementQuery,
} from "./messages.js";

// Excel
export {
  zExcelModule,
  zTaskStatus,
  zImportResult,
  zImportProgress,
  type ExcelModule,
  type TaskStatus,
  type ImportResult,
  type ImportProgress,
} from "./excel.js";
